export const ROUTES = {
  LOGIN: '/login',
  CHANGE_PASSWORD: '/change-password',
  RESET_PASSWORD: '/reset-password',
  ADMIN: {
    HOME: '/admin',
    STUDENTS: '/admin/students',
    COURSES: '/admin/courses',
    RECORDINGS: '/admin/recordings',
    BULK_UPLOAD: '/admin/bulk-upload',
    PAYMENTS: '/admin/payments',
    BUSINESS_CONFIG: '/admin/business-config',
    SESSIONS: '/admin/sessions',
    VIOLATIONS: '/admin/violations',
    TESTS: '/admin/tests',
    TESTS_NEW: '/admin/tests/new',
    QUESTIONS: '/admin/questions',
    REVIEW_QUEUE: '/admin/review-queue',
    ANALYTICS: '/admin/analytics',
    MONITORING: '/admin/monitoring',
    PERFORMANCE: '/admin/performance',
    ANNOUNCEMENTS: '/admin/announcements',
    AUDIT_LOGS: '/admin/audit-logs',
    EMAIL_LOGS: '/admin/email-logs',
  },
  STUDENT: {
    HOME: '/student',
    COURSES: '/student/courses',
    LIVE_SESSIONS: '/student/live-sessions',
    VIDEOS: '/student/videos',
    TESTS: '/student/tests',
    RESULTS: '/student/results',
    NOTIFICATIONS: '/student/notifications',
  },
} as const;

export const ROLES = {
  ADMIN: 'admin',
  STUDENT: 'student',
  TEACHER: 'teacher',
} as const;

export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    VALIDATE_SESSION: '/auth/validate-session',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
  },
  USERS: '/users',
  COURSES: '/courses',
  BATCHES: '/batches',
  LIVE_SESSIONS: '/live-sessions',
  ATTENDANCE: '/attendance',
  VIDEOS: '/videos',
  RECORDINGS: '/recordings',
  TESTS: '/tests',
  BULK_UPLOAD: '/bulk-upload',
  PAYMENTS: {
    PLANS: '/payments/plans',
    MY: '/payments/my',
    INSTALLMENTS: '/payments/installments',
  },
  EMAIL: '/email/test',
  INVOICES: '/invoices',
  ADMIN_SESSIONS: '/admin/sessions',
  ADMIN_RECORDINGS: '/admin/recordings',
  ADMIN_BATCH_CURRICULUM: '/admin/batch-curriculum',
  ADMIN_TOPICS: '/admin/topics',
  ADMIN_UPLOAD_URL: '/admin/upload-url',
  ADMIN_TESTS: '/admin/tests',
  ADMIN_TESTS_NEW: '/admin/tests/new',
  ADMIN_QUESTIONS: '/admin/questions',
  ADMIN_REVIEW_QUEUE: '/admin/review-queue',
  ADMIN_ANALYTICS: '/admin/analytics',
  ZOOM_SIGNATURE: '/zoom/signature',
  STUDENT_ACHIEVEMENTS: '/student/achievements',
  STUDENT_CERTIFICATES: '/student/certificates',
  // Phase 7A: Observability
  OBSERVABILITY_ERRORS: '/observability/errors',
  OBSERVABILITY_EVENTS: '/observability/events',
  OBSERVABILITY_METRICS: '/observability/metrics',
  OBSERVABILITY_DASHBOARD: '/observability/dashboard',
  // Phase 7C: Notifications
  ADMIN_ANNOUNCEMENTS: '/admin/announcements',
  STUDENT_NOTIFICATIONS: '/student/notifications',
  STUDENT_NOTIFICATIONS_UNREAD: '/student/notifications/unread-count',
  STUDENT_NOTIFICATIONS_READ: '/student/notifications',
  // Phase 7D: Certificate verification
  CERTIFICATE_VERIFY: '/certificates/verify',
  CERTIFICATE_STATUS: '/certificates',
  // Phase 7E: Audit
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  // Phase 7.1: Email Delivery Center
  EMAIL_LOGS: '/email-logs',
  EMAIL_LOGS_STATS: '/email-logs/stats',
  EMAIL_LOGS_ANALYTICS: '/email-logs/analytics',
  EMAIL_LOGS_QUEUE: '/email-logs/queue',
} as const;
